# Generated by Django 2.2.5 on 2019-12-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoilInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ph', models.FloatField()),
                ('Nitrogen', models.FloatField()),
                ('Phosphorus', models.FloatField()),
                ('Potassium', models.FloatField()),
                ('Temperature', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='YieldInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Crop', models.CharField(choices=[('Barley', 'Barley'), ('Wheat', 'Wheat'), ('Maize', 'Maize'), ('Sugarcane', 'Sugarcane'), ('Rice', 'Rice')], default='Barley', max_length=6)),
                ('Location', models.CharField(choices=[('AMRITSAR', 'Amritsar'), ('BARNALA', 'Barnala'), ('FARIDKOT', 'Faridkot'), ('FAZILKA', 'Fazilka'), ('FIROZEPUR', 'Firozepur'), ('GURDASPUR', 'Gurdaspur'), ('HOSHIARPUR', 'Hoshiarpur'), ('JALANDHAR', 'Jalandhar'), ('KAPURTHALA', 'Kapurthala'), ('LUDHIANA', 'Ludhiana'), ('MANSA', 'Mansa'), ('MOGA', 'Moga'), ('MUKTSAR', 'Muktsar'), ('NAWANSHAHR', 'Nawanshahr'), ('PATHANKOT', 'Pathankot'), ('PATIALA', 'Patiala'), ('RUPNAGAR', 'Rupnagar'), ('SANGRUR', 'Sangrur')], default='PATIALA', max_length=19)),
            ],
        ),
    ]
